---
version: "3"
services:
  discord-fury:
    image: nonchris/discord-fury
    container_name: discord-fury
    volumes:
      - "./data/app:/app/data:rw"
    environment:
      - UID=1000 
      - GID=1000
      - db_url=db_user:db_pw@db/db_name
      - TOKEN=
      - PREFIX=
      - OWNER_ID=
      - OWNER_NAME=
      - CHANNEL_TRACK_LIMIT=
    stdin_open: true
    tty: true
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
        - "./data/postgress:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pw
      POSTGRES_DB: db_name
    stdin_open: true
    tty: true
